application:
  name: RAGEngine
pipelines:
  pipelineDefinitions:
    documentIngestionPipeline:
      jobType: hr.combis.application.pipelines.jobs.DocumentProcessingJob
      stages:
        - documentParsingPipelineStage
        - sentenceSplittingPipelineStage
        - chunkGroupingPipelineStage